### ISSUE TITLE
pandas to optimus?

### ISSUE THREAD

**Issue by eysdevteam** [ironmussa/Optimus#364]
it isn't a issue is a question.
it's possible transform a pandas dataframe to a optimus dataframe?

**Comment by argenisleon** [comment]
Hi @eysdevteam,

To be clear, there are not Optimus dataframes just Spark dataframes.

And yes you can create Spark dataframes from Pandas
 
```
import pandas as pd
import numpy as np

data = [("bumbl#ebéé  ", 17.5, "Espionage", 7),
         ("Optim'us", 28.0, "Leader", 10),
         ("ironhide&", 26.0, "Security", 7)]
labels = ["names", "height", "function", "rank"]

# Create pandas dataframe
pdf = pd.DataFrame.from_records(data, columns=labels)

df = op.create.df(pdf = pdf)
df.table()
```

Hope this help

**Comment by argenisleon** [comment]
@eysdevteam 
Maybe you could check:

https://github.com/ironmussa/Optimus/blob/master/examples/10_min_from_spark_to_pandas_with_optimus.ipynb

This is a guide that can help you if you come form pandas.

**Comment by eysdevteam** [comment]
Ahh bien, gracias por tu ayuda. Ahora todo está más claro para mí :D

**Comment by eysdevteam** [comment]
Sorry, but when i try it i obtain this: 
i execute this: 

_import pandas as pd
import numpy as np

data = [("bumbl#ebéé  ", 17.5, "Espionage", 7),
         ("Optim'us", 28.0, "Leader", 10),
         ("ironhide&", 26.0, "Security", 7)]
labels = ["names", "height", "function", "rank"]

# Create pandas dataframe
pdf = pd.DataFrame.from_records(data, columns=labels)

df = op.create.df(pdf)_

and this ir the result: 
_TypeError: data_frame() missing 1 required positional argument: 'rows'_

**Comment by argenisleon** [comment]
@eysdevteam you need to use pdf=your_data_frame

In your case:

`df = op.create.df(pdf=pdf)`

**Comment by eysdevteam** [comment]
I don't know, but when I try, I have a error:
_df = op.create.df(pdf=pdf)_

_TypeError: data_frame() got an unexpected keyword argument 'pdf'_

but if I try with this method i don't have errors:

_df = spark.createDataFrame(pdf)_

**Comment by argenisleon** [comment]
@eysdevteam Can you check with Optimus version do you have?
>> pip show optimuspyspark

You should be working with the 2.1.1 version

Also here you can find the pandas notebook for testing.

https://hub.mybinder.org/user/ironmussa-optimus-degvd84r/notebooks/examples/10_min_from_spark_to_pandas_with_optimus.ipynb

Please let me know if could solve it
